image: registry.gitlab.com/bitfireat/davdroid:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew
  - (cd /sdk/emulator; ./emulator @test -no-audio -no-window & wait-for-emulator.sh)
  - wget -q https://f-droid.org/repo/org.dmfs.tasks_481.apk && adb install org.dmfs.tasks_481.apk

cache:
  paths:
     - .gradle/

test:
  script:
    - ./gradlew check connectedCheck
  artifacts:
    paths:
      - build/outputs/lint-results-debug.html
      - build/reports/
